"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import { QueryClient, QueryClientProvider } from "react-query";
import { usePathname } from "next/navigation";
import NavigationBar from "@/components/NavigationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const queryClient = new QueryClient();

// export const metadata: Metadata = {
//   title: "Book Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideNavBar = pathname === "/login" || pathname === "/register";

  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {!hideNavBar && <NavigationBar />}
            {children}
          </body>
        </html>
      </ThemeProvider>
    </QueryClientProvider>
  );
}
